### PR TITLE
Add to_dataframe methods to two annual count recorders.

### PR DESCRIPTION
**Pull request by jetuk**
`AnnualTotalFlowRecorder` and `AnnualCountIndexThresholdRecorder` store their data internally in an annual timeseries. This commit exposes that data as a pandas DataFrame.

### CODE REVIEW

**Review by Batch21 — COMMENTED** [review]
Changes look good. However, when a model also has a `NumpyArray*Recorder` and the `Model.to_dataframe()` method is called an error will result due to the different dataframe indexes. Might be worth adding a check in the method that returns a warning for this situation

**Comment by jetuk** [comment]
> However, when a model also has a NumpyArray*Recorder and the Model.to_dataframe() method is called an error will result due to the different dataframe indexes

Hmmm. This is already possible with FDC recorders ...

**Comment by Batch21** [comment]
Didn't think about the FDC recorders... tbh I only realised the model object had a `to_dataframe` method a couple of months ago. I haven't seen it used anywhere

**Comment by jetuk** [comment]
Sounds like we should open an issue for that bug, and decided how to fix it. This won't make anything worse in the sense that it's possible to have that method fail already.

**Review by Batch21 — APPROVED** [review]

**Comment by jetuk** [comment]
Tag #940

**Pull request merged**
