### PR TITLE
Some performance improvements

### PR DESCRIPTION
**Pull request by jetuk**
- Addresses #338 
- Adds a `CachedIndexParameter` which helps with #289 
- Cythonised `ControlCurveParameter`
- Change `self.index_parameter` cdef to `IndexParameter` for `IndexedArrayParameter`

### CODE REVIEW

**Comment by snorfalorpagus** [comment]
Is this ready for review/merge?

**Comment by jetuk** [comment]
Nope. I've done some more stuff on this branch now. Probably wait for that. I'll try and do some ASV testing of these commits.

**Comment by jetuk** [comment]
I guess we should discuss these changes?

**Comment by snorfalorpagus** [comment]
This has fallen to out of sync with the master branch. A lot of the changes aren't needed now that we've merged the component dependency tree. We should profile again, and cherry pick some useful bits from here.

**Pull request closed without merging**
