### PR TITLE
A better workaround for #470

### PR DESCRIPTION
**Pull request by jetuk**
This change the reservoir volume initialisation in the case where
max_volume is parameter. Now both `initial_volume` and
`initial_volume_pc` must be specified as floats, and are used as
is. This removes the current whitelist of acceptable parameters.

It does however mean that if the user specifies initial conditions
that are not compatible with the actual max_volume (i.e.
initial_volume != initial_volume_pc/max_volume) then there is the
possibility that parameter values will be incorrect on the first
time-step. This changes effectively makes that the users
responsibility.

### CODE REVIEW

**Comment by KevisPachos** [comment]
Hi @jetuk,
I would like to apply the new discounting functionality in a scheduling formulation. That would better show the value in delaying implementation of schemes compared to a static formulation. 
Would that require that this branch is reviewed and merged into master? If so, can I somehow help you on making this functionality available?
Thanks

**Comment by jetuk** [comment]
Yes, probably. I haven't looked at this for a while. I'll merge master here to get it up to date for you.

**Comment by KevisPachos** [comment]
Thank you @jetuk

**Comment by jetuk** [comment]
> I'll merge master here to get it up to date for you.

Done.

**Comment by Batch21** [comment]
Implementation looks good. Only comment is that the requirement to set both 'initial_volume` and `initial_volume_pc`  when `max_volume` is a parameter should probably be specified in the `Storage` docstring

**Comment by jetuk** [comment]
Thanks @Batch21. I've updated the `Storage` class docstring to include a paramters section.

**Pull request merged**
