### PR TITLE
[WIP] platypus optimisation support.

### PR DESCRIPTION
**Pull request by jetuk**
Currently does the following,

- Refactors the existing inspyred model subclass to a baseclass.
- Implements a new platypus model subclass.
- Refactors the optimisation example to use either library.

We still have no tests for the `opimisation` submodule.

### CODE REVIEW

**Comment by snorfalorpagus** [comment]
I think it should be feasible to run the examples as a test, provided we limit the number of generations and population size.

**Comment by snorfalorpagus** [comment]
Can we switch from argparse to click?

I get this error trying to use platypus (which I installed via pip).

```
Traceback (most recent call last):
  File "two_reservoir_moea.py", line 201, in <module>
    platypus_main(harmonic=args.harmonic)
  File "two_reservoir_moea.py", line 44, in platypus_main
    problem = model.setup()
  File "c:\users\snorfalorpagus\desktop\pywr\pywr\optimisation\platypus.py", line 21, in setup
    p = platypus.Problem(self._variable_map[-1], len(self._objectives), len(self._constraints))
AttributeError: module 'platypus' has no attribute 'Problem'
```

The docstring at the top will need updating.

**Comment by snorfalorpagus** [comment]
Looks like this needs the development version of Platypus (from GitHub). The version on PyPI is too old.

**Comment by snorfalorpagus** [comment]
The current setup doesn't work with the parallel executor in Platypus as it tries to pickle the Model. I think this is a more general problem - we need to ensure the flattened array of variables maps consistently across to the model parameters in the different instances.

**Comment by jetuk** [comment]
I believe the variables are sorted during caching?

I think the best way is to load the model in each instance rather than
trying to send the instance from master to all workers?

**Comment by snorfalorpagus** [comment]
> I think the best way is to load the model in each instance rather than trying to send the instance from master to all workers?
The problem with this is that the current system needs to load the model in the master node to work out how many variables/objectives the problem has.

**Comment by jetuk** [comment]
Why is that necessarily a problem? Otherwise we need to support serialisation of models? 

Generally you also need to be careful all the workers have the same instance loaded.

**Comment by snorfalorpagus** [comment]
I think we're probably both arguing the same thing here. The point I'm trying to make is that in the current setup the evaluator method which platypus uses is a method on an instance of Model. This doesn't work when you try to use Platypus in a parallel way, because it passes the evaluator method to the subprocesses via pickle, which would require the entire model to be pickled. I have a workaround for this, but it avoids using the PlatypusOptimisationModel class completely.

**Comment by jetuk** [comment]
If #601 is merged this will need updating.

**Comment by snorfalorpagus** [comment]
I do not think this should be merged in its current state anyway, due to the aforementioned issues with multiprocessing.

**Pull request closed without merging**
