### PR TITLE
Storage current_pc now accounts for min_volume != 0

### LINKED ISSUE #368: Minimum storage used by control curve parameters
Some of the control curve parameters do an interpolation when a storage falls below it's control curve, like this:

```
bottom = 0.0
weight = (current percent - bottom) / (control curve - bottom)
```

Should we be using the minimum storage attribute for the value of `bottom` instead of the control curve? Two storages with the same amount of available water could report completely different resource states.

### PR DESCRIPTION
**Pull request by jetuk**
Partially fixes #368

Change fixes `Storage`, but I'm not sure what to do about `AggregatedStorage`. @snorfalorpagus any ideas?

### CODE REVIEW

**Comment by snorfalorpagus** [comment]
I'm going to need some persuading on this. The difficultly with `AggregateStorage` highlights the non-physicalness of negative volumes.

**Comment by jetuk** [comment]
The code we have is effectively a weighted average of current %. The aggregated version could be the same approach. This way it would account for `min_volume` in a consistent manner.

**Comment by snorfalorpagus** [comment]
I think this could cause some problems for us. All of the control curves in Aquator are given in percentage assuming 0% = empty. If we change the calculation of storage percent, all the control curves will be in the wrong place in absolute terms, assuming we're using min_volume as dead storage.

**Comment by jetuk** [comment]
Do we use min_volume as dead storage? What about evaporation?

**Comment by snorfalorpagus** [comment]
I have used min_volume as dead storage in some models. Yes there is an issue with evaporation. See #332.

**Comment by jetuk** [comment]
Hmm I guess this needs some thought.

**Comment by jetuk** [comment]
So what are the choices here?

1. Define `current_pc` as based on `max_volume` and zero.
   - This means `max_volume < 0` should not be supported? Do we test for this?
   - It also means `min_volume != 0` would produce unexpected results?
   - Should it mean we don't support negative volumes at all?
2. Redefine `current_pc` to be based on `max_volume - min_volume`.
   - Different to other software. 
   - Makes non-zero hard limits in reservoirs more difficult if their control curves are 0 based proportions.
3. Add a second `current_pc` type attribute that does (2), leave `current_pc` as it is.
4. Make the choice between (1) and (2) user defined by adding a flag to the `Storage` node.
   - Potentially a performance hit for checking this during `after`?

**Comment by jetuk** [comment]
I think our consensus was to do (1) and not support negative volumes?

**Comment by snorfalorpagus** [comment]
Yes. I don't think storages with a negative volume have a sensible meaning.

I think we'll need to support some of the control curves using a non-zero value for their "bottom", but it needs to be optional.

Closing this in favour of something that makes negative min_volume invalid.

**Pull request closed without merging**
