### PR TITLE
Renamed ConstantParameter `values` to `value` in JSON

### PR DESCRIPTION
**Pull request by snorfalorpagus**
This PR renames the "values" argument to `ConstantParameter` in JSON to "value". This makes more sense to me, given that the value is singular. Previously the name was inherited from `Parameter`.

This will break a lot of existing models, although the fix is trivial. I don't know if we need to start thinking about version numbers...

An altenative approach is to support both forms ("values" AND "value").

### CODE REVIEW

**Comment by jetuk** [comment]
Is there a problem supporting both "values" and "value"?

**Comment by snorfalorpagus** [comment]
> Is there a problem supporting both "values" and "value"?

Not a technical one, no.

**Comment by snorfalorpagus** [comment]
#250.

**Comment by jetuk** [comment]
Should we support both then, or not?

**Comment by snorfalorpagus** [comment]
Let's go with both. I'll make the change.

**Pull request merged**
