### PR TITLE
Schema2 master

### PR DESCRIPTION
**Pull request by knoxsp**

### CODE REVIEW

**Comment by jetuk** [comment]
Is this just a merge of master into schema2?

**Comment by jetuk** [comment]
The tests are failing because `marshmallow` is not installed. This needs adding to the dependencies in `setup.py`; it must have got lost in the merge conflict resolution.

**Comment by knoxsp** [comment]
Yes, this is a merge from master into schema2. Marshmallow reinstated into setup.py
If this is merged, there will be a merge into schema_tsof from schema2 imminent.

**Comment by jetuk** [comment]
@knoxsp I've just merged `v1.6.0` (master) in to #641 (schema2). That should be up to date with the latest changes. The `schema_tsof` branch should no longer be required because the timestep offset stuff is in master and schema2 now.

**Pull request closed without merging**
