### PR TITLE
Displaying linear programme as table

### PR DESCRIPTION
**Pull request by snorfalorpagus**
Added function to display the linear programme as a table (#19). Needs more work on the design and wrapping to make it friendly in Jupyter.

### CODE REVIEW

**Comment by snorfalorpagus** [comment]
Also some checks on the state of the linear programme would be good - has it been solved, etc. (or even initialised).

**Comment by jetuk** [comment]
Why didn't you dump this to a dataframe and let pandas/jupyter do the HTML?

**Comment by snorfalorpagus** [comment]
> Why didn't you dump this to a dataframe and let pandas/jupyter do the HTML?

The structure didn't seem to fit in the column/row format. The matrix itself does, but then there are multiple "header" rows (objective value, upper and lower bounds, etc).

**Comment by jetuk** [comment]
Is this ready to review / merge?

**Pull request closed without merging**
