### PR TITLE
chore(release): Update changelog for 1.27.0 release.

### PR DESCRIPTION
**Pull request by jetuk**
CHANGELOG reformatted using git-cliff.

### CODE REVIEW

**Review by Batch21 — CHANGES_REQUESTED** [review]
Git cliff seems to have added lots of information for pre 1.20.0 releases and not really improved their formatting. Maybe the reformatting should be limited to 1.20.0 releases for which the conventional commit spec has generally been followed? 

Version in commit message/PR title needs updating to 1.27.0.

**Comment by jetuk** [comment]
I've redone this with a simple script to preserve the manual entries, but rewrite the conventional commits.

**Comment by jetuk** [comment]
Do you want to do #1143 , #1144 and/or #1145 before release?

**Comment by Batch21** [comment]
> Do you want to do #1143 , #1144 and/or #1145 before release?

yeah, we may as well include them

**Pull request merged**
