### PR TITLE
Fixed bug with default flow for Catchment when loading from JSON

### PR DESCRIPTION
**Pull request by jetuk**

### CODE REVIEW

**Comment by snorfalorpagus** [comment]
Is there a reason we're not using the normal Catchment `__init__` method when loading from JSON? (Don't ask me - all I did was write this function!)

**Comment by jetuk** [comment]
It's the call to `load_parameter` that needs to happen when loading the JSON.

**Comment by snorfalorpagus** [comment]
This is OK. Needs cherry picking.

**Comment by snorfalorpagus** [comment]
Merged.

**Pull request closed without merging**
