### PR TITLE
fix: Fix issue with dataframe scenario indexing

### LINKED ISSUE #1110: Multiple scenario_combinations resulting in an index error.
I have adapted one of the test models to have two scenarios, and to use combinations of the two. See below.

the key part is: `   "scenario_combinations": [[0, 0], [4, 1], [1, 0], [0, 2]],`

This results in an error:

```
  File "pywr/_model.pyx", line 628, in pywr._model.Model.run
  File "pywr/_model.pyx", line 604, in pywr._model.Model._step
  File "pywr/_model.pyx", line 825, in pywr._model.Model.before
  File "pywr/parameters/_parameters.pyx", line 76, in pywr.parameters._parameters.Parameter.calc_values
  File "pywr/parameters/_parameters.pyx", line 268, in pywr.parameters._parameters.DataFrameParameter.value
  IndexError: Out of bounds on buffer access (axis 1)
```

```json
{
    "metadata": {
        "title": "Timeseries example",
        "description": "A model with a timeseries",
        "minimum_version": "0.1"
    },
    "timestepper": {
        "start": "2025-01-01",
        "end": "2029-01-01",
        "timestep": "A"
    },
    "scenarios": [
        {
            "name": "scenario A",
            "size": 5
        },
        {
            "name": "scenario B",
            "size": 5
        }

    ],
    "scenario_combinations": [[0, 0], [4, 1], [1, 0], [0, 2]],
    "nodes": [
        {
            "name": "catchment1",
            "type": "catchment",
            "flow": "inflow"
        },
        {
            "name": "reservoir1",
            "type": "Storage",
            "initial_volume": 50.0,
            "max_volume": 9999
        },
        {
            "name": "abs1",
            "type": "link",
            "max_flow": 50
        },
        {
            "name": "demand1",
            "type": "Output",
            "max_flow": "demand",
            "cost": -10
        },
        {
            "name": "term1",
            "type": "Output",
            "cost": 5
        }
    ],
    "edges": [
        ["catchment1", "reservoir1"],
        ["reservoir1", "abs1"],
        ["abs1", "demand1"],
        ["reservoir1", "term1"]
    ],
    "parameters": {
        "inflow": {
            "type": "dataframe",
            "scenario": "scenario A",
            "data": {
                "0": {
                  "2025-01-01": 160,
                  "2026-01-01": 161,
                  "2027-01-01": 162,
                  "2028-01-01": 162,
                  "2029-01-01": 163
                },
                "1": {
                  "2025-01-01": 162,
                  "2026-01-01": 163,
                  "2027-01-01": 164,
                  "2028-01-01": 165,
                  "2029-01-01": 165
                },
                "2": {
                  "2025-01-01": 163,
                  "2026-01-01": 164,
                  "2027-01-01": 165,
                  "2028-01-01": 166,
                  "2029-01-01": 168
                },
                "3": {
                  "2025-01-01": 163,
                  "2026-01-01": 164,
                  "2027-01-01": 165,
                  "2028-01-01": 166,
                  "2029-01-01": 167
                },
                "4": {
                  "2025-01-01": 162,
                  "2026-01-01": 163,
                  "2027-01-01": 164,
                  "2028-01-01": 166,
                  "2029-01-01": 167
                }
            },
            "parse_dates": true
        },
        "demand": {
            "type": "dataframe",
            "scenario": "scenario B",
            "data": {
                "0": {
                  "2025-01-01": 10,
                  "2026-01-01": 10,
                  "2027-01-01": 10,
                  "2028-01-01": 10,
                  "2029-01-01": 10
                },
                "1": {
                  "2025-01-01": 11,
                  "2026-01-01": 11,
                  "2027-01-01": 11,
                  "2028-01-01": 11,
                  "2029-01-01": 11
                },
                "2": {
                  "2025-01-01": 12,
                  "2026-01-01": 12,
                  "2027-01-01": 12,
                  "2028-01-01": 12,
                  "2029-01-01": 12
                },
                "3": {
                  "2025-01-01": 13,
                  "2026-01-01": 13,
                  "2027-01-01": 13,
                  "2028-01-01": 13,
                  "2029-01-01": 13
                },
                "4": {
                  "2025-01-01": 14,
                  "2026-01-01": 14,
                  "2027-01-01": 14,
                  "2028-01-01": 14,
                  "2029-01-01": 14
                }
            },
            "parse_dates": true
        }
    }
}
```

### PR DESCRIPTION
**Pull request by jetuk**
Correction the look-up of dataframe data when using user combinations of scenarios.

Fixes #1110.

### CODE REVIEW

**Comment by knoxsp** [comment]
I tried to re-run the test model i posted in the issue, and have had the following error:

```
AttributeError: 'pywr.parameters._parameters.DataFrameParameter' object has no attribute '_Parameter__values'
```

This error had also been occurring on all my models from version 1.22, and on master.  I've had to revert to v1.21 to fix this issue.

**Comment by knoxsp** [comment]
```python
>>> import cython
>>> cython.__version__
'0.29.36'
```

**Comment by knoxsp** [comment]
I can confirm that my larger model runs with this fix. I have not checked whether the correct scenario data is being used. Will report back.

**Comment by knoxsp** [comment]
Confirmed that the correct scenario data is being used. Checked manually with print statements in the `value` function of the DataFrameParamter class.

**Comment by jetuk** [comment]
Do you need this back-porting to 1.21 as well?

**Comment by knoxsp** [comment]
> Do you need this back-porting to 1.21 as well?

I have upgraded cython to the latest version (3.0.4) and re-run using this branch. It now works as expected. So 1.22 doesn't work with pre-cython 3. 

I can use cython 3 so i don't need this porting back to 1.21.

**Review by Batch21 — APPROVED** [review]

**Pull request merged**
