### PR TITLE
WIP: Stop using custom manylinux images.

### PR DESCRIPTION
**Pull request by jetuk**
- Update to using manylinux2014
- The CentOS version this is derived from contains sufficiently modern GLPK and LpSolve libraries that we can just install from yum.
- No more custom manylinux images need (files removed).
- Add Python 3.9 to travis.

### CODE REVIEW

**Comment by jetuk** [comment]
This refactor has largely worked. The build is failing for lack of 3.9 wheels for PyTables. We could merge the changes to the build, and then add 3.9 later.

**Comment by jetuk** [comment]
Relevant PyTables issue about 3.9 wheels: https://github.com/PyTables/PyTables/issues/823

**Comment by amotl** [comment]
Dear James,

thanks to @avalentino, Python 3.9 wheels for Linux are available on PyPI now. See also https://github.com/PyTables/PyTables/issues/823#issuecomment-729116365.

With kind regards,
Andreas.

**Comment by jetuk** [comment]
Thanks @amotl

**Comment by jetuk** [comment]
This is now failing due to this: https://github.com/pandas-dev/pandas/issues/37795

**Comment by jetuk** [comment]
Closed in favour of #948

**Pull request closed without merging**
