### PR TITLE
Build & test Python 3.10 wheels.

### PR DESCRIPTION
**Pull request by jetuk**
This might not work just yet due to our dependencies, but we can re-run the pipeline until it does.

### CODE REVIEW

**Comment by jetuk** [comment]
This wasn't using the latest version of `cibuildwheel`. It is now and is failing to install `scipy`. They will issue wheels (1.7.2) soon. After this I will re-run the pipeline.

**Comment by jetuk** [comment]
This is now blocked by PyTables

**Comment by jetuk** [comment]
I've re-based this and enabled support for 3.9 and 3.10 builds on Windows and Linux. PyTables has released 3.7.0 which has wheels for all these platforms.

**Comment by jetuk** [comment]
This is all working now. Wheels for 3.7 to 3.10 for Windows and Linux.

**Review by Batch21 — APPROVED** [review]
Looks good. Is skipping the MUSL linux build a major issue?

**Comment by jetuk** [comment]
I believe its main use would be on Alpine Linux containers because they use
MUSL not Glibc. I think good enough for now.

**Pull request merged**
